name: Synthetic API Tests
on:
  schedule:
    - cron: 0 0 * * *

jobs:
  integration-tests:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1

      - name: "Run integration tests"
        run: cd $GITHUB_WORKSPACE/.github/workflows/synthetics && npm ci && npm run test
        env:
            GH_SYNTH_TOKEN: ${{ secrets.GH_SYNTH_TOKEN }}
            ISSUE_TITLE: "Synthetic API Tests: Unexpected response from API"
